let dataV={"nodes": [
{"name":"Pyrolysis"},
{"name":"Landfill"},
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"PP"},
{"name":"PLA"},
{"name":"Households"},
{"name":"LCUpstream"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"LABS from chemical recycling of PE"},
{"name":"C4 Gas Mixture Pyrolysis"},
{"name":"Light Liquid Fuel Pyrolysis"},
{"name":"Lactic acid from acid hydrolysis"},
{"name": "Losses"}
],
 "links": [
 {"source":"HDPE", "target":"Households", "value":0.2343, "optimal":"yes"} ,
{"source":"LDPE", "target":"Households", "value":0.6503, "optimal":"yes"} ,
{"source":"PP", "target":"Households", "value":0.0008, "optimal":"yes"} ,
{"source":"PLA", "target":"Households", "value":0.0094, "optimal":"yes"} ,
{"source":"Households", "target":"Curbside Collection", "value":0.7885, "optimal":"yes"} ,
{"source":"Households", "target":"Losses", "value":0.1062, "optimal":"yes"} ,
{"source":"Curbside Collection", "target":"Pyrolysis", "value":0.0001, "optimal":"yes"} ,
{"source":"Curbside Collection", "target":"Segregation", "value":0.7189, "optimal":"yes"} ,
{"source":"Curbside Collection", "target":"Losses", "value":0.0634, "optimal":"yes"} ,
{"source":"Segregation", "target":"Landfill", "value":0.1269, "optimal":"yes"} ,
{"source":"Segregation", "target":"LABS from chemical recycling of PE", "value":0.3806, "optimal":"yes"} ,
{"source":"Segregation", "target":"C4 Gas Mixture Pyrolysis", "value":0.0001, "optimal":"yes"} ,
{"source":"Segregation", "target":"Light Liquid Fuel Pyrolysis", "value":0.1501, "optimal":"yes"} ,
{"source":"Segregation", "target":"Lactic acid from acid hydrolysis", "value":0.0062, "optimal":"yes"},
{"source":"LCUpstream", "target":"HDPE", "value":0.00001, "optimal":"yes"} ,
{"source":"LCUpstream", "target":"LDPE", "value":0.00001, "optimal":"yes"} ,
{"target":"LCUpstream", "source":"LABS from chemical recycling of PE", "value":0.35, "optimal":"yes"} ,
{"target":"LCUpstream", "source":"C4 Gas Mixture Pyrolysis", "value":0.0001, "optimal":"yes"} ,
{"target":"LCUpstream", "source":"Light Liquid Fuel Pyrolysis", "value":0.14, "optimal":"yes"} ,
{"target":"LCUpstream", "source":"Lactic acid from acid hydrolysis", "value":0.005, "optimal":"yes"} ]};
