let dataV={"nodes": [
{"name":"LDPE"},
{"name":"PLA"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rLDPE"},
{"name":"Lumber"},
{"name":"Lactic acid from acid hydrolysis"},
{"name":"Me-Lactate from alcoholysis"},
{"name": "Losses"}
],
 "links": [
 {"source":"LDPE", "target":"Households", "value":0.0095, "optimal":"yes"} , 
{"source":"PLA", "target":"Households", "value":4.0996, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":3.6213, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.4878, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":3.3017, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.2914, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.0077, "optimal":"yes"} , 
{"source":"Segregation", "target":"Lactic acid from acid hydrolysis", "value":1.3079, "optimal":"yes"} , 
{"source":"Segregation", "target":"Me-Lactate from alcoholysis", "value":1.9862, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.0042, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Lumber", "value":0.0026, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0008, "optimal":"yes"} ]}; 
