let dataV={"nodes": [
{"name":"Landfill"},
{"name":"LDPE"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rLDPE"},
{"name":"Lumber"},
{"name":"LABS from chemical recycling of PE"},
{"name":"C4 Gas Mixture Pyrolysis"},
{"name":"Light Liquid Fuel Pyrolysis"},
{"name": "Losses"},
{"name":"LCUpstream"}
],
 "links": [
 {"source":"LDPE", "target":"Households", "value":0.7147, "optimal":"yes"} ,
{"source":"Households", "target":"Curbside Collection", "value":0.6299, "optimal":"yes"} ,
{"source":"Households", "target":"Losses", "value":0.0848, "optimal":"yes"} ,
{"source":"Curbside Collection", "target":"Landfill", "value":0.0099, "optimal":"yes"} ,
{"source":"Curbside Collection", "target":"Segregation", "value":0.5638, "optimal":"yes"} ,
{"source":"Curbside Collection", "target":"Losses", "value":0.0507, "optimal":"yes"} ,
{"source":"Segregation", "target":"Landfill", "value":0.0995, "optimal":"yes"} ,
{"source":"Segregation", "target":"rLDPE", "value":0.0539, "optimal":"yes"} ,
{"source":"Segregation", "target":"LABS from chemical recycling of PE", "value":0.2134, "optimal":"yes"} ,
{"source":"Segregation", "target":"C4 Gas Mixture Pyrolysis", "value":0.0056, "optimal":"yes"} ,
{"source":"Segregation", "target":"Light Liquid Fuel Pyrolysis", "value":0.1472, "optimal":"yes"} ,
{"source":"rLDPE", "target":"LDPE", "value":0.0296, "optimal":"yes"} ,
{"source":"rLDPE", "target":"Lumber", "value":0.0183, "optimal":"yes"} ,
{"source":"rLDPE", "target":"Losses", "value":0.0059, "optimal":"yes"} ,
{"source":"LABS from chemical recycling of PE", "target":"LCUpstream", "value":0.2134, "optimal":"yes"} ,
{"source":"C4 Gas Mixture Pyrolysis", "target":"LCUpstream", "value":0.0056, "optimal":"yes"} ,
{"source":"Light Liquid Fuel Pyrolysis", "target":"LCUpstream", "value":0.1472, "optimal":"yes"} ]};
