let dataV={"nodes": [
{"name":"Landfill"},
{"name":"LDPE"},
{"name":"PP"},
{"name":"PLA"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rLDPE"},
{"name":"rPP"},
{"name":"Lumber"},
{"name":"Lactic acid from acid hydrolysis"},
{"name":"Me-Lactate from alcoholysis"},
{"name": "Losses"},
{"name":"LCUpstream"}
],
 "links": [
 {"source":"LDPE", "target":"Households", "value":0.3807, "optimal":"yes"} ,
{"source":"PP", "target":"Households", "value":0.0158, "optimal":"yes"} ,
{"source":"PLA", "target":"Households", "value":1.89, "optimal":"yes"} ,
{"source":"Households", "target":"Curbside Collection", "value":1.4596, "optimal":"yes"} ,
{"source":"Households", "target":"Losses", "value":0.8269, "optimal":"yes"} ,
{"source":"Curbside Collection", "target":"Segregation", "value":1.3307, "optimal":"yes"} ,
{"source":"Curbside Collection", "target":"Losses", "value":0.1174, "optimal":"yes"} ,
{"source":"Segregation", "target":"Landfill", "value":0.2349, "optimal":"yes"} ,
{"source":"Segregation", "target":"rLDPE", "value":0.1825, "optimal":"yes"} ,
{"source":"Segregation", "target":"rPP", "value":0.0076, "optimal":"yes"} ,
{"source":"Segregation", "target":"Lactic acid from acid hydrolysis", "value":0.0005, "optimal":"yes"} ,
{"source":"Segregation", "target":"Me-Lactate from alcoholysis", "value":0.9054, "optimal":"yes"} ,
{"source":"rLDPE", "target":"LDPE", "value":0.1004, "optimal":"yes"} ,
{"source":"rLDPE", "target":"Lumber", "value":0.062, "optimal":"yes"} ,
{"source":"rLDPE", "target":"Losses", "value":0.0201, "optimal":"yes"} ,
{"source":"rPP", "target":"PP", "value":0.0042, "optimal":"yes"} ,
{"source":"rPP", "target":"Lumber", "value":0.0028, "optimal":"yes"} ,
{"source":"rPP", "target":"Losses", "value":0.0006, "optimal":"yes"},
{"source":"LCUpstream", "target":"PLA", "value":0.00001, "optimal":"yes"} ,
{"source":"LCUpstream", "target":"LDPE", "value":0.00001, "optimal":"yes"} ,
{"target":"LCUpstream", "source":"Me-Lactate from alcoholysis", "value":0.90, "optimal":"yes"} ,
{"target":"LCUpstream", "source":"Lactic acid from acid hydrolysis", "value":0.0005, "optimal":"yes"} ]};

