let dataV={"nodes": [
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"PLA"},
{"name":"Households"},
{"name":"LCUpstream"},
{"name":"Curbside Collection"},
{"name":"Dropoff"},
{"name":"Segregation"},
{"name":"rHDPE"},
{"name":"rPLA"},
{"name":"LABS from chemical recycling of PE"},
{"name":"Light Liquid Fuel Pyrolysis"},
{"name":"Lactic acid from acid hydrolysis"},
{"name": "Losses"}
],
 "links": [
 {"source":"HDPE", "target":"Households", "value":0.0521, "optimal":"yes"} ,
{"source":"LDPE", "target":"Households", "value":0.5583, "optimal":"yes"} ,
{"source":"PLA", "target":"Households", "value":0.8285, "optimal":"yes"} ,
{"source":"Households", "target":"Curbside Collection", "value":1.2676, "optimal":"yes"} ,
{"source":"Households", "target":"Dropoff", "value":0.0006, "optimal":"yes"} ,
{"source":"Households", "target":"Losses", "value":0.1708, "optimal":"yes"} ,
{"source":"Curbside Collection", "target":"Landfill", "value":0.0055, "optimal":"yes"} ,
{"source":"Curbside Collection", "target":"Segregation", "value":1.1499, "optimal":"yes"} ,
{"source":"Curbside Collection", "target":"Losses", "value":0.102, "optimal":"yes"} ,
{"source":"Dropoff", "target":"Segregation", "value":0.0005, "optimal":"yes"} ,
{"source":"Dropoff", "target":"Losses", "value":0.0001, "optimal":"yes"} ,
{"source":"Segregation", "target":"Landfill", "value":0.203, "optimal":"yes"} ,
{"source":"Segregation", "target":"rHDPE", "value":0.0168, "optimal":"yes"} ,
{"source":"Segregation", "target":"rPLA", "value":0.0085, "optimal":"yes"} ,
{"source":"Segregation", "target":"LABS from chemical recycling of PE", "value":0.2631, "optimal":"yes"} ,
{"source":"Segregation", "target":"Light Liquid Fuel Pyrolysis", "value":0.0935, "optimal":"yes"} ,
{"source":"Segregation", "target":"Lactic acid from acid hydrolysis", "value":0.5369, "optimal":"yes"} ,
{"source":"rHDPE", "target":"Incineration", "value":0.006, "optimal":"yes"} ,
{"source":"rHDPE", "target":"HDPE", "value":0.0092, "optimal":"yes"} ,
{"source":"rHDPE", "target":"Losses", "value":0.0015, "optimal":"yes"} ,
{"source":"rPLA", "target":"Incineration", "value":0.0066, "optimal":"yes"} ,
{"source":"rPLA", "target":"PLA", "value":0.0013, "optimal":"yes"} ,
{"source":"rPLA", "target":"Losses", "value":0.0006, "optimal":"yes"},
{"source":"LCUpstream", "target":"HDPE", "value":0.00001, "optimal":"yes"} ,
{"source":"LCUpstream", "target":"LDPE", "value":0.00001, "optimal":"yes"} ,
{"target":"LCUpstream", "source":"LABS from chemical recycling of PE", "value":0.00001, "optimal":"yes"} ,
{"target":"LCUpstream", "source":"Light Liquid Fuel Pyrolysis", "value":0.00001, "optimal":"yes"} ,
{"target":"LCUpstream", "source":"Lactic acid from acid hydrolysis", "value":0.00001, "optimal":"yes"} ]};

