let dataV={"nodes": [
{"name":"LDPE"},
{"name":"PLA"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rLDPE"},
{"name":"Lumber"},
{"name":"Lactic acid from acid hydrolysis"},
{"name":"Me-Lactate from alcoholysis"},
{"name": "Losses"},
{"name":"Value-chain Upstream"} 
],
 "links": [
 {"source":"LDPE", "target":"Households", "value":0.5987, "optimal":"yes"} , 
{"source":"PLA", "target":"Households", "value":0.6745, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":1.122, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.1511, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":1.023, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.0903, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.4811, "optimal":"yes"} , 
{"source":"Segregation", "target":"Lactic acid from acid hydrolysis", "value":0.2462, "optimal":"yes"} , 
{"source":"Segregation", "target":"Me-Lactate from alcoholysis", "value":0.2958, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.2646, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Lumber", "value":0.1636, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0529, "optimal":"yes"} ,
{"source":"Value-chain Upstream", "target":"LDPE", "value":0.001, "optimal":"yes"} ,
{"source":"Value-chain Upstream", "target":"PLA", "value":0.001, "optimal":"yes"} ,
{"source":"Lactic acid from acid hydrolysis", "target":"Value-chain Upstream", "value":0.2462, "optimal":"yes"} ,
{"source":"Me-Lactate from alcoholysis", "target":"Value-chain Upstream", "value":0.2958, "optimal":"yes"} ]}; 
