let dataV={"nodes": [
{"name":"Landfill"},
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"PP"},
{"name":"PLA"},
{"name":"Paper"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rPaper"},
{"name":"LABS from chemical recycling of PE"},
{"name":"C4 Gas Mixture Pyrolysis"},
{"name":"Light Liquid Fuel Pyrolysis"},
{"name":"Lactic acid from acid hydrolysis"},
{"name": "Losses"}
],
 "links": [
 {"source":"HDPE", "target":"Households", "value":0.2499, "optimal":"yes"} ,
{"source":"LDPE", "target":"Households", "value":0.5929, "optimal":"yes"} ,
{"source":"PP", "target":"Households", "value":0.0662, "optimal":"yes"} ,
{"source":"PLA", "target":"Households", "value":0.0789, "optimal":"yes"} ,
{"source":"Paper", "target":"Households", "value":0.0401, "optimal":"yes"} ,
{"source":"Households", "target":"Curbside Collection", "value":0.9059, "optimal":"yes"} ,
{"source":"Households", "target":"Losses", "value":0.122, "optimal":"yes"} ,
{"source":"Curbside Collection", "target":"Segregation", "value":0.826, "optimal":"yes"} ,
{"source":"Curbside Collection", "target":"Losses", "value":0.0729, "optimal":"yes"} ,
{"source":"Segregation", "target":"Landfill", "value":0.1458, "optimal":"yes"} ,
{"source":"Segregation", "target":"rPaper", "value":0.0265, "optimal":"yes"} ,
{"source":"Segregation", "target":"LABS from chemical recycling of PE", "value":0.36, "optimal":"yes"} ,
{"source":"Segregation", "target":"C4 Gas Mixture Pyrolysis", "value":0.0066, "optimal":"yes"} ,
{"source":"Segregation", "target":"Light Liquid Fuel Pyrolysis", "value":0.1718, "optimal":"yes"} ,
{"source":"Segregation", "target":"Lactic acid from acid hydrolysis", "value":0.0522, "optimal":"yes"} ,
{"source":"rPaper", "target":"Paper", "value":0.0262, "optimal":"yes"} ,
{"source":"rPaper", "target":"Losses", "value":0.0003, "optimal":"yes"} ]};
